services:
  api:
    build: .
    environment:
      POSTGRES_SERVER: db
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15.18-trixie
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "strong"
      POSTGRES_DB: "fastship"
    ports:
      - "5433:5432"
