"""changed spelling

Revision ID: 09f70e06ffbc
Revises: b3132919343d
Create Date: 2026-06-14 00:32:59.868214

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09f70e06ffbc'
down_revision: Union[str, Sequence[str], None] = 'b3132919343d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner', sa.Column('servicable_zip_codes', sa.ARRAY(sa.INTEGER()), nullable=True))
    op.drop_column('delivery_partner', 'servicable_zip_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner', sa.Column('servicable_zip_code', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('delivery_partner', 'servicable_zip_codes')
    # ### end Alembic commands ###
