"""Added Tags

Revision ID: 5669dcdafd8b
Revises: 259fd0b5a1c8
Create Date: 2026-06-23 17:32:17.666649

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from app.database.models import TagName

# revision identifiers, used by Alembic.
revision: str = "5669dcdafd8b"
down_revision: Union[str, Sequence[str], None] = "259fd0b5a1c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "name",
            sa.Enum(
                "EXPRESS",
                "STANDARD",
                "FRAGILE",
                "HEAVY",
                "INTERNATIONAL",
                "DOMESTIC",
                "TEMPERATURE_CONTROLLED",
                "GIFT",
                "RETURN",
                "DOCUMENTS",
                name="tagname",
            ),
            nullable=False,
        ),
        sa.Column("instruction", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shipment_tag",
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("shipment_id", "tag_id"),
    )
    # ### end Alembic commands ###

    ### Add tag entries in the databse ###
    op.execute(
        "INSERT INTO tag (id, name, instruction) VALUES "
        "(gen_random_uuid(), 'EXPRESS', 'Prioritize for next available dispatch and expedited delivery.')"
    )
    op.execute(
        "INSERT INTO tag (id, name, instruction) VALUES "
        "(gen_random_uuid(), 'STANDARD', 'Process via the regular delivery schedule.')"
    )
    op.execute(
        "INSERT INTO tag (id, name, instruction) VALUES "
        "(gen_random_uuid(), 'FRAGILE', 'Handle with care, mark as fragile, and avoid stacking heavy items on top.')"
    )
    op.execute(
        "INSERT INTO tag (id, name, instruction) VALUES "
        "(gen_random_uuid(), 'HEAVY', 'Use appropriate lifting equipment and assign two-person handling.')"
    )
    op.execute(
        "INSERT INTO tag (id, name, instruction) VALUES "
        "(gen_random_uuid(), 'INTERNATIONAL', 'Attach customs documentation and verify destination import requirements.')"
    )
    op.execute(
        "INSERT INTO tag (id, name, instruction) VALUES "
        "(gen_random_uuid(), 'DOMESTIC', 'Route through the domestic carrier network.')"
    )
    op.execute(
        "INSERT INTO tag (id, name, instruction) VALUES "
        "(gen_random_uuid(), 'TEMPERATURE_CONTROLLED', 'Store and transport within the required temperature range using refrigerated handling.')"
    )
    op.execute(
        "INSERT INTO tag (id, name, instruction) VALUES "
        "(gen_random_uuid(), 'GIFT', 'Apply gift wrapping and exclude any pricing information from the package.')"
    )
    op.execute(
        "INSERT INTO tag (id, name, instruction) VALUES "
        "(gen_random_uuid(), 'RETURN', 'Process as a return shipment and route back to the originating warehouse.')"
    )
    op.execute(
        "INSERT INTO tag (id, name, instruction) VALUES "
        "(gen_random_uuid(), 'DOCUMENTS', 'Handle as document-only shipment and keep contents flat and dry.')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shipment_tag")
    op.drop_table("tag")
    # ### end Alembic commands ###
